vich_uploader:
    db_driver: orm

    mappings:
        hopital_images:
            uri_prefix: uploads/images/hopitals
            upload_destination: '%kernel.project_dir%/public/uploads/images/hopitals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true 